### ISSUE TITLE
Add PYPI token to repo secrets

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-login-python#2]
- @kshitijrajsharma I have migrated your repo to be under HOTOSM (I hope you are ok with that).
- We will keep your published package in pypi.
- To continue publishing this way we need your PYPI_TOKEN variable set in this repo's secrets.

**Comment by kshitijrajsharma** [comment]
oh , you can do that ?  That's strange haha ! No worries

**Comment by kshitijrajsharma** [comment]
Added Token to github secrets , now you can use github workflow for release

**Comment by spwoodcock** [comment]
All good keeping the same token!

Could you add Rob or me to the pypi project collaborators as a backup though? Always good to have a second in case someone is unavailable for a bit =)

**Comment by kshitijrajsharma** [comment]
sure , attach me your pypi username

**Comment by spwoodcock** [comment]
spwoodcock 👍

**Comment by kshitijrajsharma** [comment]
Invitation sent !
